### ISSUE TITLE
deepin下运行报错

### ISSUE THREAD

**Issue by aohanhongzhi** [seecode-audit/seecode-scanner#3]
[14:39:37] [INFO] [ScanProject] Start syncing project code into the scan directory...
[14:39:37] [INFO] [ScanProject] Synchronization project code completion.
[14:39:37] [INFO] [ScanProject] Start executing exclusion rules...
[14:39:37] [INFO] [ScanProject] Exclusion rule execution completed.
[14:39:37] [INFO] [ScanProject] Start analyzing components...
[14:39:37] [/usr/local/lib/python3.6/dist-packages/clocwalk/cli.py(70)start()] [INFO] analysis statistics code ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/clocwalk/cli.py", line 85, in start
    tag_filter=self.tag_filter
  File "/usr/local/lib/python3.6/dist-packages/clocwalk/plugins/nodejs.py", line 55, in start
    result.extend(_get_dependencies(file_name=item, origin=relative_path))
  File "/usr/local/lib/python3.6/dist-packages/clocwalk/plugins/nodejs.py", line 21, in _get_dependencies
    for name, ver in json_obj[tag].items():
KeyError: 'devDependencies'
[14:39:39] [/usr/local/lib/python3.6/dist-packages/clocwalk/cli.py(92)start()] [CRITICAL] exception occurred while running script for 'JavaScript' (''devDependencies'')
[14:39:39] [INFO] [ScanProject] Project code line: [209484], language: [Java], size: [131344] KB
[14:39:39] [WARNING] [ScanProject] No related dependencies found!!!
[14:39:39] [INFO] [ScanProject] Start executing exclusion rules...
[14:39:40] [INFO] [ScanProject] Exclusion rule execution completed.
[14:39:40] [INFO] [RuleScanner] Begin to perform rule-based component vulnerability analysis...
[14:39:40] [INFO] [RuleScanner] Rule component scan completed.
[14:39:40] [INFO] [RuleScanner] 正在执行黑名单检测...
[14:39:40] [INFO] [RuleScanner] Begin to perform rule-based blacklist vulnerability analysis...
[14:39:40] [INFO] [RuleScanner] Rule blacklist scan completed.
[14:39:40] [INFO] [PluginScanner] 正在执行黑名单检测...
[14:39:40] [INFO] [RuleScanner] 正在执行白名单过滤...
[14:39:40] [INFO] [RuleScanner] False positive rule processing...
[14:39:40] [INFO] [RuleScanner] Rule whitelist scan completed.
[14:39:40] [INFO] [PluginScanner] 正在执行白名单过滤...
[14:39:40] [INFO] [PluginScanner] False positive plugin processing...
[14:39:40] [INFO] [PluginScanner] Plugin whitelist scan completed.
[14:39:40] [INFO] [ScanProject] [+] Save the scan log to '/data/seecode/logs/findbugs/20191017143937.log'.
[14:39:40] [INFO] [ScanProject] [+] Save the scan results to '/data/seecode/logs/findbugs/findbugs.json', total: 0.
[14:39:40] [INFO] Analysis completed, time consuming: 3.69s

**Comment by MyKings** [comment]
这个报错是 [clocwalk](https://github.com/seecode-audit/clocwalk) 的报错，不会影响正常扫描
